defaults:
  -
    values:
      title: HackOn
      tagline: A Pan-India Virtual Hackathon
      daterange: 11th April 2020 to 19th April 2020
      assets:
        small_logo: './assets/img/main-logo.svg'
        logo: './assets/img/main-logo.svg'
      socials:
        devfolio: https://guide.devfolio.co/appendix/c-apply-with-devfolio-button-integration
        discord: https://discord.hackon.tech/
        workshops: https://forms.gle/QFUvfQrgmaRuBNoy6
        telegram: https://telegram.hackon.tech/

        schedule:


collections_dir: _collections

collections:
  - faq
